[launcher]
version = 0.0.14
description = Splunk Add-on for Graph API Endpoints

[id]
version = 0.0.14
name = graph_api_endpoints

[install]
build = 1771845975
is_configured = false
state = enabled

[package]
id = graph_api_endpoints
check_for_updates = true

[ui]
label = Splunk Add-on for Graph API Endpoints
supported_themes = light, dark
is_visible = true

[triggers]
reload.graph_api_endpoints_settings = simple
reload.graph_api_endpoints_account = simple
