[admin:graph_api_endpoints]
match = /
members = graph_api_endpoints_account, graph_api_endpoints_graph_api_endpoints, graph_api_endpoints_settings

[admin_external:graph_api_endpoints_account]
handlertype = python
python.version = python3
handlerfile = graph_api_endpoints_rh_account.py
handleractions = edit, list, remove, create
handlerpersistentmode = true

[admin_external:graph_api_endpoints_settings]
handlertype = python
python.version = python3
handlerfile = graph_api_endpoints_rh_settings.py
handleractions = edit, list
handlerpersistentmode = true

[admin_external:graph_api_endpoints_graph_api_endpoints]
handlertype = python
python.version = python3
handlerfile = graph_api_endpoints_rh_graph_api_endpoints.py
handleractions = edit, list, remove, create
handlerpersistentmode = true
