[expose:graph_api_endpoints_account]
pattern = graph_api_endpoints_account
methods = POST, GET

[expose:graph_api_endpoints_account_specified]
pattern = graph_api_endpoints_account/*
methods = POST, GET, DELETE

[expose:graph_api_endpoints_settings]
pattern = graph_api_endpoints_settings
methods = POST, GET

[expose:graph_api_endpoints_settings_specified]
pattern = graph_api_endpoints_settings/*
methods = POST, GET, DELETE

[expose:graph_api_endpoints_graph_api_endpoints]
pattern = graph_api_endpoints_graph_api_endpoints
methods = POST, GET

[expose:graph_api_endpoints_graph_api_endpoints_specified]
pattern = graph_api_endpoints_graph_api_endpoints/*
methods = POST, GET, DELETE
